version: "3.8"
networks:
  web-app-connection:
    driver: bridge
  go-server-connection:
    driver: bridge
services:
  web-application:
    container_name: web-application
    depends_on:
      - go-server
    expose:
      - "3000"
    networks:
      - web-app-connection
      - go-server-connection
    env_file:
      - ./web-application/.env
    build: ./web-application
    restart: always
  go-server:
    container_name: go-server
    expose:
      - "8443"
    env_file:
      - ./go-server/.env
    networks:
      - go-server-connection
    build: ./go-server
    restart: always
  nginx:
    ports:
      - "80:80"
      - "443:443"
    build:
      dockerfile: ./nginx.Dockerfile
    networks:
      - web-app-connection
      - go-server-connection
