version: "3.8"
services:
  web-application:
    depends_on:
      - go-server
    ports:
      - "80:3000"
    env_file:
      - ./web-application/.env
    build: ./web-application
    restart: always
  go-server:
    ports:
      - "8080:8080"
    env_file:
      - ./go-server/.env
    build: ./go-server
    restart: always

    # tty: true
    # command: tail -F anything

    # volumes:
    #   - ./go-server:/app
    # depends_on:
    #   - db
