version: "3.8"
services:
  web-application:
    depends_on:
      - go-server
    ports:
      - "3000:3000"
    env_file:
      - ./web-application/.env
    build: ./web-application
    restart: always
  go-server:
    ports:
      - "8443:8443"
    env_file:
      - ./go-server/.env
    build: ./go-server
    restart: always
  nginx:
    dockerfile: ./nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    # tty: true
    # command: tail -F anything

    # volumes:
    #   - ./go-server:/app
    # depends_on:
    #   - db
