version: "3.8"
services:
  frontend:
    depends_on:
      - backend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    build: ./frontend
    restart: always
  backend:
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    build: ./backend
    restart: always

    # tty: true
    # command: tail -F anything

    # volumes:
    #   - ./backend:/app
    # depends_on:
    #   - db
